name: busana_nusantara
description: A quiz game about Indonesian traditional clothing
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.0
  shared_preferences: ^2.2.0
  audioplayers: ^6.0.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  http: ^1.2.0
  fl_chart: ^0.68.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/questions.json
    - assets/audio/